/*
 * Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing AprendizProcessInstructorApi
    /// </summary>
    public sealed class AprendizProcessInstructorApiTests : ApiTestsBase
    {
        private readonly IAprendizProcessInstructorApi _instance;

        public AprendizProcessInstructorApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IAprendizProcessInstructorApi>();
        }

        /// <summary>
        /// Test ApiAprendizProcessInstructorGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiAprendizProcessInstructorGetAsyncTest()
        {
            var response = await _instance.ApiAprendizProcessInstructorGetAsync();
            var model = response.Ok();
            Assert.IsType<List<AprendizProcessInstructorDto>>(model);
        }

        /// <summary>
        /// Test ApiAprendizProcessInstructorIdDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiAprendizProcessInstructorIdDeleteAsyncTest()
        {
            int id = default!;
            await _instance.ApiAprendizProcessInstructorIdDeleteAsync(id);
        }

        /// <summary>
        /// Test ApiAprendizProcessInstructorIdGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiAprendizProcessInstructorIdGetAsyncTest()
        {
            int id = default!;
            var response = await _instance.ApiAprendizProcessInstructorIdGetAsync(id);
            var model = response.Ok();
            Assert.IsType<AprendizProcessInstructorDto>(model);
        }

        /// <summary>
        /// Test ApiAprendizProcessInstructorIdPut
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiAprendizProcessInstructorIdPutAsyncTest()
        {
            int id = default!;
            Client.Option<AprendizProcessInstructorDto> aprendizProcessInstructorDto = default!;
            var response = await _instance.ApiAprendizProcessInstructorIdPutAsync(id, aprendizProcessInstructorDto);
            var model = response.Ok();
            Assert.IsType<AprendizProcessInstructorDto>(model);
        }

        /// <summary>
        /// Test ApiAprendizProcessInstructorPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiAprendizProcessInstructorPostAsyncTest()
        {
            Client.Option<AprendizProcessInstructorDto> aprendizProcessInstructorDto = default!;
            var response = await _instance.ApiAprendizProcessInstructorPostAsync(aprendizProcessInstructorDto);
            var model = response.Created();
            Assert.IsType<AprendizProcessInstructorDto>(model);
        }
    }
}
