/*
 * Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing FormModuleApi
    /// </summary>
    public sealed class FormModuleApiTests : ApiTestsBase
    {
        private readonly IFormModuleApi _instance;

        public FormModuleApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IFormModuleApi>();
        }

        /// <summary>
        /// Test ApiFormModuleGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiFormModuleGetAsyncTest()
        {
            var response = await _instance.ApiFormModuleGetAsync();
            var model = response.Ok();
            Assert.IsType<List<FormModuleDto>>(model);
        }

        /// <summary>
        /// Test ApiFormModuleIdDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiFormModuleIdDeleteAsyncTest()
        {
            int id = default!;
            await _instance.ApiFormModuleIdDeleteAsync(id);
        }

        /// <summary>
        /// Test ApiFormModuleIdGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiFormModuleIdGetAsyncTest()
        {
            int id = default!;
            var response = await _instance.ApiFormModuleIdGetAsync(id);
            var model = response.Ok();
            Assert.IsType<FormModuleDto>(model);
        }

        /// <summary>
        /// Test ApiFormModuleIdPatch
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiFormModuleIdPatchAsyncTest()
        {
            int id = default!;
            Client.Option<FormModuleDto> formModuleDto = default!;
            var response = await _instance.ApiFormModuleIdPatchAsync(id, formModuleDto);
            var model = response.Ok();
            Assert.IsType<FormModuleDto>(model);
        }

        /// <summary>
        /// Test ApiFormModuleIdPut
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiFormModuleIdPutAsyncTest()
        {
            int id = default!;
            Client.Option<FormModuleDto> formModuleDto = default!;
            var response = await _instance.ApiFormModuleIdPutAsync(id, formModuleDto);
            var model = response.Ok();
            Assert.IsType<FormModuleDto>(model);
        }

        /// <summary>
        /// Test ApiFormModulePost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiFormModulePostAsyncTest()
        {
            Client.Option<FormModuleDto> formModuleDto = default!;
            var response = await _instance.ApiFormModulePostAsync(formModuleDto);
            var model = response.Created();
            Assert.IsType<FormModuleDto>(model);
        }
    }
}
