/*
 * Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing ModuleApi
    /// </summary>
    public sealed class ModuleApiTests : ApiTestsBase
    {
        private readonly IModuleApi _instance;

        public ModuleApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IModuleApi>();
        }

        /// <summary>
        /// Test ApiModuleGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiModuleGetAsyncTest()
        {
            var response = await _instance.ApiModuleGetAsync();
            var model = response.Ok();
            Assert.IsType<List<ModuleDto>>(model);
        }

        /// <summary>
        /// Test ApiModuleIdDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiModuleIdDeleteAsyncTest()
        {
            int id = default!;
            await _instance.ApiModuleIdDeleteAsync(id);
        }

        /// <summary>
        /// Test ApiModuleIdGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiModuleIdGetAsyncTest()
        {
            int id = default!;
            var response = await _instance.ApiModuleIdGetAsync(id);
            var model = response.Ok();
            Assert.IsType<ModuleDto>(model);
        }

        /// <summary>
        /// Test ApiModuleIdPatch
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiModuleIdPatchAsyncTest()
        {
            int id = default!;
            Client.Option<ModuleDto> moduleDto = default!;
            var response = await _instance.ApiModuleIdPatchAsync(id, moduleDto);
            var model = response.Ok();
            Assert.IsType<ModuleDto>(model);
        }

        /// <summary>
        /// Test ApiModuleIdPut
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiModuleIdPutAsyncTest()
        {
            int id = default!;
            Client.Option<ModuleDto> moduleDto = default!;
            var response = await _instance.ApiModuleIdPutAsync(id, moduleDto);
            var model = response.Ok();
            Assert.IsType<ModuleDto>(model);
        }

        /// <summary>
        /// Test ApiModuleIdSoftDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiModuleIdSoftDeleteAsyncTest()
        {
            int id = default!;
            await _instance.ApiModuleIdSoftDeleteAsync(id);
        }

        /// <summary>
        /// Test ApiModulePost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiModulePostAsyncTest()
        {
            Client.Option<ModuleDto> moduleDto = default!;
            var response = await _instance.ApiModulePostAsync(moduleDto);
            var model = response.Created();
            Assert.IsType<ModuleDto>(model);
        }
    }
}
