/*
 * Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing PersonApi
    /// </summary>
    public sealed class PersonApiTests : ApiTestsBase
    {
        private readonly IPersonApi _instance;

        public PersonApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IPersonApi>();
        }

        /// <summary>
        /// Test ApiPersonGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiPersonGetAsyncTest()
        {
            var response = await _instance.ApiPersonGetAsync();
            var model = response.Ok();
            Assert.IsType<List<PersonDto>>(model);
        }

        /// <summary>
        /// Test ApiPersonIdDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiPersonIdDeleteAsyncTest()
        {
            int id = default!;
            await _instance.ApiPersonIdDeleteAsync(id);
        }

        /// <summary>
        /// Test ApiPersonIdGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiPersonIdGetAsyncTest()
        {
            int id = default!;
            var response = await _instance.ApiPersonIdGetAsync(id);
            var model = response.Ok();
            Assert.IsType<PersonDto>(model);
        }

        /// <summary>
        /// Test ApiPersonIdPatch
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiPersonIdPatchAsyncTest()
        {
            int id = default!;
            Client.Option<PersonDto> personDto = default!;
            var response = await _instance.ApiPersonIdPatchAsync(id, personDto);
            var model = response.Ok();
            Assert.IsType<PersonDto>(model);
        }

        /// <summary>
        /// Test ApiPersonIdPut
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiPersonIdPutAsyncTest()
        {
            int id = default!;
            Client.Option<PersonDto> personDto = default!;
            var response = await _instance.ApiPersonIdPutAsync(id, personDto);
            var model = response.Ok();
            Assert.IsType<PersonDto>(model);
        }

        /// <summary>
        /// Test ApiPersonIdSoftDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiPersonIdSoftDeleteAsyncTest()
        {
            int id = default!;
            await _instance.ApiPersonIdSoftDeleteAsync(id);
        }

        /// <summary>
        /// Test ApiPersonPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiPersonPostAsyncTest()
        {
            Client.Option<PersonDto> personDto = default!;
            var response = await _instance.ApiPersonPostAsync(personDto);
            var model = response.Created();
            Assert.IsType<PersonDto>(model);
        }
    }
}
