/*
 * Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing RolUserApi
    /// </summary>
    public sealed class RolUserApiTests : ApiTestsBase
    {
        private readonly IRolUserApi _instance;

        public RolUserApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IRolUserApi>();
        }

        /// <summary>
        /// Test ApiRolUserGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiRolUserGetAsyncTest()
        {
            var response = await _instance.ApiRolUserGetAsync();
            var model = response.Ok();
            Assert.IsType<List<UserRolDto>>(model);
        }

        /// <summary>
        /// Test ApiRolUserIdDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiRolUserIdDeleteAsyncTest()
        {
            int id = default!;
            await _instance.ApiRolUserIdDeleteAsync(id);
        }

        /// <summary>
        /// Test ApiRolUserIdGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiRolUserIdGetAsyncTest()
        {
            int id = default!;
            var response = await _instance.ApiRolUserIdGetAsync(id);
            var model = response.Ok();
            Assert.IsType<UserRolDto>(model);
        }

        /// <summary>
        /// Test ApiRolUserIdPut
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiRolUserIdPutAsyncTest()
        {
            int id = default!;
            Client.Option<UserRolDto> userRolDto = default!;
            var response = await _instance.ApiRolUserIdPutAsync(id, userRolDto);
            var model = response.Ok();
            Assert.IsType<UserRolDto>(model);
        }

        /// <summary>
        /// Test ApiRolUserPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiRolUserPostAsyncTest()
        {
            Client.Option<UserRolDto> userRolDto = default!;
            var response = await _instance.ApiRolUserPostAsync(userRolDto);
            var model = response.Created();
            Assert.IsType<UserRolDto>(model);
        }
    }
}
