/*
 * Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing UserApi
    /// </summary>
    public sealed class UserApiTests : ApiTestsBase
    {
        private readonly IUserApi _instance;

        public UserApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IUserApi>();
        }

        /// <summary>
        /// Test ApiUserGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiUserGetAsyncTest()
        {
            var response = await _instance.ApiUserGetAsync();
            var model = response.Ok();
            Assert.IsType<List<UserDto>>(model);
        }

        /// <summary>
        /// Test ApiUserIdActivatePost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiUserIdActivatePostAsyncTest()
        {
            int id = default!;
            await _instance.ApiUserIdActivatePostAsync(id);
        }

        /// <summary>
        /// Test ApiUserIdDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiUserIdDeleteAsyncTest()
        {
            int id = default!;
            await _instance.ApiUserIdDeleteAsync(id);
        }

        /// <summary>
        /// Test ApiUserIdGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiUserIdGetAsyncTest()
        {
            int id = default!;
            var response = await _instance.ApiUserIdGetAsync(id);
            var model = response.Ok();
            Assert.IsType<UserDto>(model);
        }

        /// <summary>
        /// Test ApiUserIdPatch
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiUserIdPatchAsyncTest()
        {
            int id = default!;
            Client.Option<UserDto> userDto = default!;
            var response = await _instance.ApiUserIdPatchAsync(id, userDto);
            var model = response.Ok();
            Assert.IsType<UserDto>(model);
        }

        /// <summary>
        /// Test ApiUserIdPut
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiUserIdPutAsyncTest()
        {
            int id = default!;
            Client.Option<UserDto> userDto = default!;
            var response = await _instance.ApiUserIdPutAsync(id, userDto);
            var model = response.Ok();
            Assert.IsType<UserDto>(model);
        }

        /// <summary>
        /// Test ApiUserIdSoftDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiUserIdSoftDeleteAsyncTest()
        {
            int id = default!;
            await _instance.ApiUserIdSoftDeleteAsync(id);
        }

        /// <summary>
        /// Test ApiUserPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiUserPostAsyncTest()
        {
            Client.Option<UserDto> userDto = default!;
            var response = await _instance.ApiUserPostAsync(userDto);
            var model = response.Created();
            Assert.IsType<UserDto>(model);
        }
    }
}
