/*
 * Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing EnterpriseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EnterpriseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EnterpriseDto
        //private EnterpriseDto instance;

        public EnterpriseDtoTests()
        {
            // TODO uncomment below to create an instance of EnterpriseDto
            //instance = new EnterpriseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EnterpriseDto
        /// </summary>
        [Fact]
        public void EnterpriseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" EnterpriseDto
            //Assert.IsType<EnterpriseDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Observation'
        /// </summary>
        [Fact]
        public void ObservationTest()
        {
            // TODO unit test for the property 'Observation'
        }

        /// <summary>
        /// Test the property 'NameEnterprise'
        /// </summary>
        [Fact]
        public void NameEnterpriseTest()
        {
            // TODO unit test for the property 'NameEnterprise'
        }

        /// <summary>
        /// Test the property 'PhoneEnterprise'
        /// </summary>
        [Fact]
        public void PhoneEnterpriseTest()
        {
            // TODO unit test for the property 'PhoneEnterprise'
        }

        /// <summary>
        /// Test the property 'Locate'
        /// </summary>
        [Fact]
        public void LocateTest()
        {
            // TODO unit test for the property 'Locate'
        }

        /// <summary>
        /// Test the property 'NitEnterprise'
        /// </summary>
        [Fact]
        public void NitEnterpriseTest()
        {
            // TODO unit test for the property 'NitEnterprise'
        }

        /// <summary>
        /// Test the property 'EmailEnterprise'
        /// </summary>
        [Fact]
        public void EmailEnterpriseTest()
        {
            // TODO unit test for the property 'EmailEnterprise'
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
    }
}
