/*
 * Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing FormModuleDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FormModuleDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FormModuleDto
        //private FormModuleDto instance;

        public FormModuleDtoTests()
        {
            // TODO uncomment below to create an instance of FormModuleDto
            //instance = new FormModuleDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FormModuleDto
        /// </summary>
        [Fact]
        public void FormModuleDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" FormModuleDto
            //Assert.IsType<FormModuleDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'StatusProcedure'
        /// </summary>
        [Fact]
        public void StatusProcedureTest()
        {
            // TODO unit test for the property 'StatusProcedure'
        }

        /// <summary>
        /// Test the property 'FormId'
        /// </summary>
        [Fact]
        public void FormIdTest()
        {
            // TODO unit test for the property 'FormId'
        }

        /// <summary>
        /// Test the property 'ModuleId'
        /// </summary>
        [Fact]
        public void ModuleIdTest()
        {
            // TODO unit test for the property 'ModuleId'
        }
    }
}
