/*
 * Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing FormDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FormDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FormDto
        //private FormDto instance;

        public FormDtoTests()
        {
            // TODO uncomment below to create an instance of FormDto
            //instance = new FormDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FormDto
        /// </summary>
        [Fact]
        public void FormDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" FormDto
            //Assert.IsType<FormDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Cuestion'
        /// </summary>
        [Fact]
        public void CuestionTest()
        {
            // TODO unit test for the property 'Cuestion'
        }

        /// <summary>
        /// Test the property 'TypeCuestion'
        /// </summary>
        [Fact]
        public void TypeCuestionTest()
        {
            // TODO unit test for the property 'TypeCuestion'
        }

        /// <summary>
        /// Test the property 'Answer'
        /// </summary>
        [Fact]
        public void AnswerTest()
        {
            // TODO unit test for the property 'Answer'
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
    }
}
