/*
 * Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RolFormDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RolFormDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RolFormDto
        //private RolFormDto instance;

        public RolFormDtoTests()
        {
            // TODO uncomment below to create an instance of RolFormDto
            //instance = new RolFormDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RolFormDto
        /// </summary>
        [Fact]
        public void RolFormDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" RolFormDto
            //Assert.IsType<RolFormDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Permission'
        /// </summary>
        [Fact]
        public void PermissionTest()
        {
            // TODO unit test for the property 'Permission'
        }

        /// <summary>
        /// Test the property 'RolId'
        /// </summary>
        [Fact]
        public void RolIdTest()
        {
            // TODO unit test for the property 'RolId'
        }

        /// <summary>
        /// Test the property 'FormId'
        /// </summary>
        [Fact]
        public void FormIdTest()
        {
            // TODO unit test for the property 'FormId'
        }
    }
}
