/*
 * Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SedeDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SedeDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SedeDto
        //private SedeDto instance;

        public SedeDtoTests()
        {
            // TODO uncomment below to create an instance of SedeDto
            //instance = new SedeDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SedeDto
        /// </summary>
        [Fact]
        public void SedeDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" SedeDto
            //Assert.IsType<SedeDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'CodeSede'
        /// </summary>
        [Fact]
        public void CodeSedeTest()
        {
            // TODO unit test for the property 'CodeSede'
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'PhoneSede'
        /// </summary>
        [Fact]
        public void PhoneSedeTest()
        {
            // TODO unit test for the property 'PhoneSede'
        }

        /// <summary>
        /// Test the property 'EmailContact'
        /// </summary>
        [Fact]
        public void EmailContactTest()
        {
            // TODO unit test for the property 'EmailContact'
        }

        /// <summary>
        /// Test the property 'CenterId'
        /// </summary>
        [Fact]
        public void CenterIdTest()
        {
            // TODO unit test for the property 'CenterId'
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
    }
}
