/*
 * Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing UserSedeDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserSedeDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserSedeDto
        //private UserSedeDto instance;

        public UserSedeDtoTests()
        {
            // TODO uncomment below to create an instance of UserSedeDto
            //instance = new UserSedeDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserSedeDto
        /// </summary>
        [Fact]
        public void UserSedeDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserSedeDto
            //Assert.IsType<UserSedeDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'StatusProcedure'
        /// </summary>
        [Fact]
        public void StatusProcedureTest()
        {
            // TODO unit test for the property 'StatusProcedure'
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'SedeId'
        /// </summary>
        [Fact]
        public void SedeIdTest()
        {
            // TODO unit test for the property 'SedeId'
        }
    }
}
