// <auto-generated>
/*
 * Web
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CenterDto
    /// </summary>
    public partial class CenterDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CenterDto" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="name">name</param>
        /// <param name="codeCenter">codeCenter</param>
        /// <param name="active">active</param>
        /// <param name="regionalId">regionalId</param>
        /// <param name="address">address</param>
        [JsonConstructor]
        public CenterDto(Option<int?> id = default, Option<string?> name = default, Option<string?> codeCenter = default, Option<bool?> active = default, Option<int?> regionalId = default, Option<string?> address = default)
        {
            IdOption = id;
            NameOption = name;
            CodeCenterOption = codeCenter;
            ActiveOption = active;
            RegionalIdOption = regionalId;
            AddressOption = address;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of CodeCenter
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CodeCenterOption { get; private set; }

        /// <summary>
        /// Gets or Sets CodeCenter
        /// </summary>
        [JsonPropertyName("codeCenter")]
        public string? CodeCenter { get { return this.CodeCenterOption; } set { this.CodeCenterOption = new(value); } }

        /// <summary>
        /// Used to track the state of Active
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ActiveOption { get; private set; }

        /// <summary>
        /// Gets or Sets Active
        /// </summary>
        [JsonPropertyName("active")]
        public bool? Active { get { return this.ActiveOption; } set { this.ActiveOption = new(value); } }

        /// <summary>
        /// Used to track the state of RegionalId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> RegionalIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets RegionalId
        /// </summary>
        [JsonPropertyName("regionalId")]
        public int? RegionalId { get { return this.RegionalIdOption; } set { this.RegionalIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Address
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AddressOption { get; private set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [JsonPropertyName("address")]
        public string? Address { get { return this.AddressOption; } set { this.AddressOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CenterDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  CodeCenter: ").Append(CodeCenter).Append("\n");
            sb.Append("  Active: ").Append(Active).Append("\n");
            sb.Append("  RegionalId: ").Append(RegionalId).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CenterDto" />
    /// </summary>
    public class CenterDtoJsonConverter : JsonConverter<CenterDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="CenterDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CenterDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<string?> name = default;
            Option<string?> codeCenter = default;
            Option<bool?> active = default;
            Option<int?> regionalId = default;
            Option<string?> address = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                id = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "codeCenter":
                            codeCenter = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "active":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                active = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "regionalId":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                regionalId = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "address":
                            address = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class CenterDto.");

            if (active.IsSet && active.Value == null)
                throw new ArgumentNullException(nameof(active), "Property is not nullable for class CenterDto.");

            if (regionalId.IsSet && regionalId.Value == null)
                throw new ArgumentNullException(nameof(regionalId), "Property is not nullable for class CenterDto.");

            return new CenterDto(id, name, codeCenter, active, regionalId, address);
        }

        /// <summary>
        /// Serializes a <see cref="CenterDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="centerDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CenterDto centerDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, centerDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CenterDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="centerDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CenterDto centerDto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (centerDto.IdOption.IsSet)
                writer.WriteNumber("id", centerDto.IdOption.Value!.Value);

            if (centerDto.NameOption.IsSet)
                if (centerDto.NameOption.Value != null)
                    writer.WriteString("name", centerDto.Name);
                else
                    writer.WriteNull("name");

            if (centerDto.CodeCenterOption.IsSet)
                if (centerDto.CodeCenterOption.Value != null)
                    writer.WriteString("codeCenter", centerDto.CodeCenter);
                else
                    writer.WriteNull("codeCenter");

            if (centerDto.ActiveOption.IsSet)
                writer.WriteBoolean("active", centerDto.ActiveOption.Value!.Value);

            if (centerDto.RegionalIdOption.IsSet)
                writer.WriteNumber("regionalId", centerDto.RegionalIdOption.Value!.Value);

            if (centerDto.AddressOption.IsSet)
                if (centerDto.AddressOption.Value != null)
                    writer.WriteString("address", centerDto.Address);
                else
                    writer.WriteNull("address");
        }
    }
}
